[colors.primary]
background = "0x1e1e2e"
foreground = "0xc0caf5"

[font.normal]
family = "Monospace"

[window]
dynamic_title = true

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
key = "C"
mods = "Control|Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Alt"
action = "Paste"
